---
title: "Chapter 3 - Data Visualization: Sections 3.1 to 3.4"
author: "SUNDAY ADETUNJI"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Section 3.1 – Introduction

```{r}
head(mpg)  # View the first 6 rows of mpg dataset
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

## Section 3.2.4 – Exercises

```{r}
ggplot(data = mpg)
```

```{r}
dim(mpg)
```

```{r}
# Check documentation for 'drv'
# Run in console: ?mpg
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = class, y = drv))
```

## Section 3.3 – Aesthetic Mappings

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

## Section 3.3.1 – Exercises

```{r}
# Incorrect usage
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
```

```{r}
# Correct usage
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

```{r}
str(mpg)
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = cty))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, size = cty))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = factor(cty)))
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class, shape = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class), stroke = 2)
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, colour = displ < 5))
```

## Section 3.4 – Common Problems

```{r}
# WRONG: + must not start a line
# ggplot(data = mpg) 
# + geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
# CORRECT:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```
